version: "3.4"
services:
  telegram-bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: tverio/link-ripper-bot
    env_file:
      - ./.env
    ports:
      - 8080:8080
      - 5050:5050
    volumes:
      - telegram-bot-logs:/usr/share/app/logs
    networks:
      backend: { aliases: [ripper.backend] }

networks:
  backend:
    driver: bridge

volumes:
  telegram-bot-logs:
