package io.tver.telegram.rebrandly.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.Optional;

/**
 * Create a new link request
 * https://developers.rebrandly.com/docs/create-a-new-link
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@JsonInclude(JsonInclude.Include.NON_EMPTY)
public class LinkRequest {
    /**
     * destination string required
     * UTF8
     * Valid URL
     * Max 2048 chars The destination URL you want your branded short link to point to
     *
     */
    @JsonProperty(required = true)
    private String destination;
    /**
     * slashtag string optional
     * Allowed character set:
     * A-Z, a-z, 0-9, _, -
     * Min 1 chars
     * Max 40 chars	The keyword portion of your branded short link. If not specified, will be autogenerated.
     */
    private String slashtag;
    /**
     * title string optional
     * UTF8
     * Min 3 chars
     * Max 255 chars A title you assign to the branded short link in order to remember what's behind it
     *
     */
    private String title;
    /**
     * description string optional
     * Min 3 chars
     * Max 2000 chars Available only if your plan includes link notes
     *
     */
    private String description;
    /**
     * domain object optional
     * Domain Reference A reference to the branded domain resource for this branded short link.
     * If not set, http://rebrand.ly is used
     */
    private Optional<Domain> domain;

    @Data
    @Builder
    @AllArgsConstructor
    @NoArgsConstructor
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    public static class Domain {
        private String fullName;
    }
}
